name: Blog tests
on:
  push:
    branches: [ FinalProject ]
    
jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./Front
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: run back end test
      run: ./ExecBack.sh
      timeout-minutes: 30